### ISSUE TITLE
wireguard Makefile arch/arm64/Makefile: No such file or directory

### ISSUE THREAD

**Issue by pho3nixf1re** [klutchell/balena-wireguard#1]
I copied your files into my own balena services repo and it seems to be failing at the following step:

```dockerfile
RUN make -C /usr/src/kernel_modules_headers M=/app/wireguard-linux-compat/src -j"$(nproc)"
```

```
[Build]   wireguard Step 11/14 : RUN make -C /usr/src/kernel_modules_headers M=/app/wireguard-linux-compat/src -j"$(nproc)"
[Build]   wireguard  ---> Running in 5300603ff05a
[Build]   wireguard make: Entering directory '/usr/src/kernel_modules_headers'
[Build]   wireguard Makefile:614: arch/arm64/Makefile: No such file or directory
[Build]   wireguard make: *** No rule to make target 'arch/arm64/Makefile'.  Stop.
```
Just for reference here is my entire dockerfile just in case I broke something.

```dockerfile
# https://www.balena.io/blog/how-to-run-wireguard-vpn-in-balenaos/

FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:build as build

RUN install_packages curl build-essential libelf-dev libssl-dev pkg-config git flex bison bc python kmod

WORKDIR /usr/src

ENV BALENA_MACHINE_NAME "%%BALENA_MACHINE_NAME%%"
ENV VERSION "2.51.1+rev1.prod"

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN curl -L "https://files.balena-cloud.com/images/${BALENA_MACHINE_NAME}/${VERSION/+/%2B}/kernel_modules_headers.tar.gz" | tar xvz

RUN make -C /usr/src/kernel_modules_headers -j"$(nproc)" modules_prepare

FROM linuxserver/wireguard:arm64v8-latest

COPY --from=build /usr/src/kernel_modules_headers/ /usr/src/kernel_modules_headers/

RUN make -C /usr/src/kernel_modules_headers M=/app/wireguard-linux-compat/src -j"$(nproc)"

COPY insmod.sh /

RUN chmod +x /insmod.sh

ENTRYPOINT [ "/bin/bash", "-c", "/insmod.sh && /init" ]

```

I'm not really sure why that last build step is failing. I'm not really familiar with what is going on there.

**Comment by klutchell** [comment]
It looks like you have the correct details, but I found it to be very unreliable as to which kernel headers (platform & version) provided by balena actually have the correct Makefile included. It was a bit of trial and error unfortunately.

For example, when I went to the latest revision `2.51.1+rev1.prod` as you have also done I found the `raspberrypi3-64` kernel headers did not have the correct Makefile, but the `raspberrypi3` kernel headers did.

I'm actually running this version at home today:
https://github.com/klutchell/balena-pihole-unbound/blob/master/wireguard/Dockerfile

So I'm not sure what to suggest besides experimenting with different combinations of `BALENA_MACHINE_NAME` and `VERSION` until you find one that works. In your case I would try changing your app from 64-bit to standard Raspberry Pi 3.

You could also bring it up on the balena forums when you find kernel headers that do not support compilation. I probably should have done that myself when I first noticed.

**Comment by pho3nixf1re** [comment]
Thanks for the great response! I'll revert my change of the target version to the one you had and then also report it in the forums. Might be worth adding some of this detail to the readme or as a comment to the version set in the dockerfile.

**Comment by klutchell** [comment]
Leave me a link to your forum post and I'll add it to the README!
