### ISSUE TITLE
QR codes are not shown, qrencode is not installed

### ISSUE THREAD

**Issue by inxbit** [klutchell/balena-wireguard#87]
qrencode is not installed so the QR codes are not shown, when running the command `show-peer 1` for example.

Peers can still be configured by copy pasting the configuration files's content, but the QRCode is very convenient.

Thanks,

CD

**Comment by klutchell** [comment]
Good catch, `qrencode` used to be part of [libqrencode](https://pkgs.alpinelinux.org/package/v3.18/community/x86_64/libqrencode) but now it's part of [libqrencode-tools](https://pkgs.alpinelinux.org/package/v3.19/community/x86_64/libqrencode-tools).
